### ISSUE TITLE
CI failing - stable and git builds fail to launch on ArchLinux

### ISSUE THREAD

**Issue by pyamsoft** [LizardByte/pacman-repo#39]
### Describe the Bug

Hello maintainers, this is just a notification for you in case you are not aware of the recent state of sunshine on ArchLinux.

ArchLinux has recently bumped its soname version for `libminiupnpc` from 19 to 21

Attempting to launch `sushine` via `systemctl --user start sunshine.service` shows the following error in console

```
/usr/bin/sunshine: error while loading shared libraries: libminiupnpc.so.19: cannot open shared object file: No such file or directory
```

The CI builds that would normally fix sunshine by rebuilding daily have been failing, so a new build is not created with a new linked soname.

---

Downgrading the library soname version is not possible, as ArchLinux does not support "partial upgrades" and other packages on the system rely on the new version.

### Expected Behavior

- I would expect the daily CI that rebuilds the package to account for library changes to succeed.
- Once succeeded, I would expect the systemctl service to start sunshine correctly, as it did before the miniupnpc update.

### Additional Context

Thank you for your work and dedication to this project!

**Comment by mudkipme** [comment]
It seems AUR has a patch for this:
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=sunshine&id=ac7eb819f0501b77f34f659e1dbc260138377f71

**Comment by takelur** [comment]
If you're not using the AUR, the ABI seems mostly backwards compatible in my testing. I can confirm that as a temporary fix creating a symlink from .so.19 to .so.21 allows Sunshine to run again on my system:
`ln -s /usr/lib/libminiupnpc.so.21 /usr/lib/libminiupnpc.so.19`

Other Arch packages should already be using .so.21, but this could break any other software you have specifically requiring .so.19.

**Comment by ReenigneArcher** [comment]
beta should be fixed now

**Comment by christianjanev** [comment]
I still get the same error after installing sunshine from the beta repo
